mail_subject: 'lins接口自动化测试报告'
sender_mail_address: 'xxxx@xxxx.com'
sender_username: 'xxxx@xxxx.com'
sender_password: PeeuobDpukzEcD54
receiver_mail_list: [ 'xxxx@xxxx.com', ]
smtp_domain: 'smtp.exmail.qq.com'
smtp_port: 465